---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: front-end
  namespace: dev
spec:
  # type: NodePort
  # type: LoadBalancer # expose the frontend service through a load balancer instead of a NodePort; because the nodes in the eks are not in the public subnet therefore they do not have any public IPs
  type: ClusterIP # expose front-end via ingress
  ports:
  - port: 80
    targetPort: 8079
    # nodePort: 30001
    protocol: TCP
  selector:
    name: front-end
