---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
#   annotations:
# {{ toYaml .Values.ingress.annotations | indent 4 }}
#   labels:
# {{ toYaml .Values.ingress.labels | indent 4 }}
  name: socks-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - hosts:
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80